/**
 * Workspace Core — Slack-like collaborative workspace types shared between
 * server, plugins, and the React UI.
 *
 * These are the canonical types for channels, messages, members, reactions,
 * and per-user read state. The Workspace Core (Phase 11) backs them with the
 * existing `business_entities` table using `moduleKey: "workspace"`.
 *
 * All entities are company-scoped — there is no cross-tenant access.
 */

// ---------------------------------------------------------------------------
// Channels
// ---------------------------------------------------------------------------

/**
 * A channel's visibility / behaviour class.
 *
 * - `public`  — everyone in the company sees and may post (default).
 * - `private` — only listed members may see / post.
 * - `dm`      — direct message between exactly two members; addressed by
 *               `dmKey`.
 * - `system`  — read-only feed populated by automation (events, alerts).
 */
export type ChannelKind = "public" | "private" | "dm" | "system";

export interface WorkspaceChannel {
  id: string;
  companyId: string;
  /** Short, URL-safe identifier (`"sales"`, `"general"`, `"ai-team"`). */
  slug: string;
  name: string;
  nameAr?: string;
  description?: string;
  kind: ChannelKind;
  /** For DM channels: sorted member IDs joined with `"_"`. */
  dmKey?: string;
  archived: boolean;
  /** When true, new company members are auto-added on join. */
  defaultMembers: boolean;
  /** Pinned topic / banner displayed at the top of the channel. */
  topicPin?: string;
  createdAt: string;
  createdBy?: string;
  /** Cached counters; refreshed on read. */
  memberCount: number;
  messageCount: number;
  /** Per-request: number of unread messages for the requesting member. */
  unreadCount?: number;
  lastMessageAt?: string;
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

/**
 * Top-level discriminator for what a message represents:
 *
 * - `text`            — ordinary human / agent prose.
 * - `system`          — internal system note (joins, archives, etc.).
 * - `event`           — emitted by the Hermes / business event bridge.
 * - `card`            — wraps a smart card payload (`card` field).
 * - `command_result`  — output of a `/slash` command.
 * - `ai_response`     — generated by an AI member.
 */
export type MessageKind =
  | "text"
  | "system"
  | "event"
  | "card"
  | "command_result"
  | "ai_response";

export interface WorkspaceMessageAttachment {
  url: string;
  name: string;
  type: string;
  size?: number;
}

/**
 * Action button rendered on a smart card. The action key is interpreted by
 * the card host (P11-C); the foundation only stores the descriptor.
 */
export interface WorkspaceMessageCardAction {
  key: string;
  label: string;
  labelAr?: string;
  danger?: boolean;
}

export interface WorkspaceMessageCard {
  entityType: string;
  entityId: string;
  actions?: WorkspaceMessageCardAction[];
  snapshot?: Record<string, unknown>;
}

export interface WorkspaceMessageMention {
  type: "user" | "agent" | "channel";
  /** For `user` / `agent`: the member ID. For `channel`: the channel ID. */
  id: string;
}

export interface WorkspaceMessage {
  id: string;
  companyId: string;
  channelId: string;
  /** For replies: the thread root message ID. */
  threadRootId?: string;
  kind: MessageKind;
  authorType: "user" | "agent" | "hermes" | "system";
  /**
   * The composite member ID: `userId` for humans, `agent:<slug>` for AI
   * agents, `hermes:<id>` for Hermes-bridge actors, or `"system"`.
   */
  authorId: string;
  authorDisplayName?: string;
  /** Emoji glyph or remote avatar URL. */
  authorAvatar?: string;
  /** Markdown allowed. */
  body: string;
  bodyAr?: string;
  attachments?: WorkspaceMessageAttachment[];
  /** Smart card payload (filled by P11-C; the foundation only persists it). */
  card?: WorkspaceMessageCard;
  mentions?: WorkspaceMessageMention[];
  /** Emoji glyph → list of member IDs that reacted. */
  reactions?: Record<string, string[]>;
  editedAt?: string;
  deletedAt?: string;
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Members (humans + agents + hermes)
// ---------------------------------------------------------------------------

export type MemberType = "user" | "agent" | "hermes";

export type WorkspaceMemberStatus =
  | "online"
  | "away"
  | "busy"
  | "offline"
  | "working";

export interface WorkspaceMember {
  /** `userId` | `agent:<slug>` | `hermes:<id>`. */
  id: string;
  companyId: string;
  type: MemberType;
  displayName: string;
  displayNameAr?: string;
  /** Emoji or URL. */
  avatar?: string;
  title?: string;
  status: WorkspaceMemberStatus;
  statusMessage?: string;
  /** For agents: the matching `BusinessAgentDefinition.slug`. */
  agentSlug?: string;
  /** IDs of channels the member belongs to. */
  channelMemberships?: string[];
  lastSeenAt?: string;
}

// ---------------------------------------------------------------------------
// Read state & reactions (typed for clarity; persisted via business_entities)
// ---------------------------------------------------------------------------

export interface ChannelReadState {
  channelId: string;
  memberId: string;
  lastReadMessageId?: string;
  lastReadAt: string;
}

export interface MessageReaction {
  messageId: string;
  emoji: string;
  memberIds: string[];
}

// ---------------------------------------------------------------------------
// Real-time stream events
// ---------------------------------------------------------------------------

export type WorkspaceStreamEvent =
  | { kind: "message.created"; channelId: string; message: WorkspaceMessage }
  | { kind: "message.updated"; channelId: string; message: WorkspaceMessage }
  | { kind: "message.deleted"; channelId: string; messageId: string }
  | {
      kind: "reaction.added";
      channelId: string;
      messageId: string;
      emoji: string;
      memberId: string;
    }
  | {
      kind: "reaction.removed";
      channelId: string;
      messageId: string;
      emoji: string;
      memberId: string;
    }
  | { kind: "channel.created"; channel: WorkspaceChannel }
  | { kind: "channel.updated"; channel: WorkspaceChannel }
  | {
      kind: "member.status_changed";
      memberId: string;
      status: WorkspaceMemberStatus;
      message?: string;
    }
  | { kind: "typing"; channelId: string; memberId: string };

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Marker stored in `businessEntities.moduleKey` for all workspace rows. */
export const WORKSPACE_MODULE_KEY = "workspace";

/** Entity type discriminators for workspace rows. */
export const WORKSPACE_ENTITY_TYPES = {
  channel: "channel",
  message: "message",
  member: "member",
  readState: "read_state",
} as const;

export type WorkspaceEntityType =
  (typeof WORKSPACE_ENTITY_TYPES)[keyof typeof WORKSPACE_ENTITY_TYPES];

/**
 * Compute the deterministic DM channel key for two members.
 *
 * The result is stable regardless of argument order so callers can use it for
 * idempotent lookups (`channels.findOrCreateDm`).
 */
export function computeDmKey(memberA: string, memberB: string): string {
  return [memberA, memberB].slice().sort().join("_");
}

/**
 * Reserved channel slugs that come with every company. Useful for the seed
 * pipeline and any UI surface that wants to bootstrap nav before the API
 * call completes.
 */
export const DEFAULT_CHANNEL_SLUGS = [
  "general",
  "announcements",
  "sales",
  "finance",
  "support",
  "operations",
  "ai-team",
  "leadership",
] as const;

export type DefaultChannelSlug = (typeof DEFAULT_CHANNEL_SLUGS)[number];
